name: "dev"
on:
  push:
    branches-ignore:
      - staging
      - main
jobs:
  deploy:
    name: Run dev tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: What is happening
        run: |
          echo "We're not deploying anything, just testing"
      - name: List workspace files
        run: |
          ls -ld ${{github.workspace}}