name: "dev"
on:
  push:
    branches-ignore:
      - staging
      - main
jobs:
  deploy:
    name: Run dev tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: List vendor folder
        run: |
          echo "We're not deploying anything"
          ls -ld ${{github.workspace}}